services:
  - type: web
    name: lung-cancer-risk-predictor
    env: python
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: HUGGINGFACE_API_KEY
        value: "https://api-inference.huggingface.co/models/mixtralai/Mixtral-8x7B-Instruct-v0.1"
